version: 2.1
orbs:
  node: circleci/node@4.3.0

jobs:
  test:
    executor:
      name: node/default
    steps:
      - node/test:
          pkg-manager: yarn

workflows:
  node-tests:
    jobs:
      - test
