name: CI

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: run install script
        run: node scripts/install.js
      - name: lint
        run: npm run lint

  typecheck_tests:
    name: Typecheck tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: run install script
        run: node scripts/install.js
      - name: Build tests
        run: npm run build-test

  test_windows:
    name: Test on Windows with Node 10
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: run install script
        run: node scripts/install.js
      - name: Run tests
        run: npm run test

  test_macos:
    name: Test on MacOS with Node 10
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: run install script
        run: node scripts/install.js
      - name: Run tests
        run: npm run test

  test_linux:
    name: Test on Linux with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install vyper
        run: docker pull ethereum/vyper:0.1.0b10
      - name: install
        run: npm install
      - name: run install script
        run: node scripts/install.js
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: run install script
        run: node scripts/install.js
      - name: Run tests
        run: npm run test
